#
# (с) 2020 gSpot (https://github.com/gSpotx2f/ruantiblock_openwrt)
#

include $(TOPDIR)/rules.mk

PKG_VERSION:=0.9.0
PKG_RELEASE:=1
LUCI_TITLE:=Translation for luci-app-ruantiblock - Русский (Russian)
LUCI_DEPENDS:=+luci-app-ruantiblock
LUCI_PKGARCH:=all

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
