#!/bin/sh

UCI_CMD=`which uci`
if [ $? -ne 0 ]; then
    echo " Error! UCI doesn't exists" >&2
    exit 1
fi
RUAB_CMD="/usr/bin/ruantiblock"
PROXY_MODE=`$UCI_CMD get ruantiblock.config.proxy_mode`
IF_VPN=`$UCI_CMD get ruantiblock.config.if_vpn`
VPN_ROUTE_CHECK=`$UCI_CMD get ruantiblock.config.vpn_route_check`

[ "$VPN_ROUTE_CHECK" != "0" ] && exit 0

if [ "$ACTION" = "ifup" ] && [ "$PROXY_MODE" = "2" ] && [ "$DEVICE" = "$IF_VPN" ]; then
	if [ `$RUAB_CMD raw-status` -ne 2 ]; then
		sleep 5
		$RUAB_CMD reload
	fi
fi
